site_name: OVHcloud TechLabs - Workbooks
site_description: Comprehensive tutorials and workbooks for OVHcloud TechLabs
site_url: https://cougz.github.io/ovhcloud-workbooks

theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
    - navigation.indexes
    - content.tabs.link
  logo: assets/logo.svg

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: 🇺🇸 English
          build: true
        - locale: fr
          name: 🇫🇷 Français
          build: true
        - locale: de
          name: 🇩🇪 Deutsch
          build: true

nav:
  - Home: index.md
  - Public Cloud:
    - public-cloud/index.md
    - AI Endpoints:
      - public-cloud/ai-endpoints/index.md
      - RAG Tutorial:
        - public-cloud/ai-endpoints/rag-tutorial/index.md
        - Setup Guide: public-cloud/ai-endpoints/rag-tutorial/setup-guide.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
